Add full-width numbers support for Time, Date, DateTime, DateRange
taiga-family/maskito pull request #1043
Opened 2024-02-10 16:30 UTC by rikusen0335

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring
- [ ] Build or CI related changes
- [ ] Tests related changes
- [ ] Documentation content changes

## What is the current behaviour?

Closes #884

This PR implements full-width to half-width preprocessor into time, or datetime or almost similar masks.

Please see issue page for more detail

## What is the new behaviour?

Above masks will have full-width to half-width preprocessor.

## Implementation
- Moved `createFullWidthToHalfWidthPreprocessor` from `projects/kit/src/lib/masks/number/processors` to `projects/kit/src/lib/processors` (also tests)
- Added `createFullWidthToHalfWidthPreprocessor` to `Time`, `Date`, `DateTime`, `DateRange` masks
- ~~Added e2e tests for `Time`, `Date`, `DateTime`, `DateRange` masks~~ _WIP_

2024-02-10 16:33 UTC, rikusen0335 commented
@nsbarsukov
Made a tests for Date or Time related, please review this when you have a time :)

2024-02-12 09:00 UTC, nsbarsukov requested changes

2024-02-13 22:45 UTC, rikusen0335 commented on projects/kit/src/lib/masks/date-range/date-range-mask.ts
> +import {createFullWidthToHalfWidthPreprocessor} from '../number/processors';
Oh, sorry it accidently revert the changes. Will work on this

2024-02-17 16:25 UTC, rikusen0335 commented
Okay, now I added colon convert preprocessor to `Time` and `DateTime` masks.

2024-02-19 10:13 UTC, nsbarsukov approved these changes

2024-02-19 10:14 UTC, merged

2024-02-19 10:14 UTC, nsbarsukov commented
@rikusen0335 Thanks ❤️

2024-02-19 11:25 UTC, rikusen0335 commented
Congrats! 🎉